name: Update PR with docker image

on:
  workflow_run:
    workflows: ["Create and publish a Docker image to Dockerhub", "Create and publish a Docker image to GitHub Packages"]
    types:
      - completed
  pull_request:
    types: [opened, reopened]

jobs:
    comment-pr:
        runs-on: ubuntu-latest
        name: Upsert comment on the PR
        steps:
            - uses: thollander/actions-comment-pull-request@v2
              with:
                message: |
                    :robot: A Docker image for this PR is available to test with:
                    
                    ## GitHub Packages
                    ```bash
                    docker run --rm -v ./config:/config -v ./logs:/config/logs ghcr.io/rfsbraz/deleterr:pr-${{ github.event.pull_request.number }} -e LOG_LEVEL=DEBUG
                    ```

                    ## Dockerhub
                    ```bash
                    docker run --rm -v ./config:/config -v ./logs:/config/logs rfsbraz/deleterr:pr-${{ github.event.pull_request.number }} -e LOG_LEVEL=DEBUG
                    ```
                comment_tag: docker_image_instructions